services:
  db:
      image: mysql:8.0
      container_name: adm_db_itau
      ports:
        - '3307:3306'
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: backdb
        MYSQL_PASSWORD: root
      networks:
        - net_itau
  rabbitmq:
      image: rabbitmq:management-alpine
      ports:
        - '5672:5672'
        - '15672:15672'
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      networks:
        - net_itau
networks:
    net_itau: